import './globals.css'
import { Inter } from 'next/font/google'
import { Provider } from './provide'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Toque de Ouro -Lingerie',
  description: 'Generated by Vitor Manoel',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
