import './globals.css'
import { Inter } from 'next/font/google'
import { Provider } from './provide'
import MiniMenu from './MiniMenu'
import { Sacola } from './Sacola'
import Popup_Sacola from './Popup_Sacola'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Toque de Ouro -Lingerie',
  description: 'Generated by Vitor Manoel',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Sacola></Sacola>
          <Popup_Sacola></Popup_Sacola>
          <MiniMenu></MiniMenu>
          {children}
        </Provider>
      </body>
    </html>
  )
}
